### ISSUE TITLE
'gg ez' gets recognised in strings like 'Chegg ezang'

### ISSUE THREAD

**Issue by ricklancee** [ChaosTheDude/GGEZBot#1]
`gg ez` gets recognised in strings like `Chegg ezang`. Using a regex with word boundaries like `/\b(gg ez)\b/i` (or something else) would result in better matching.  

https://regex101.com/r/eA4zR7/3

example: https://www.reddit.com/r/Overwatch/comments/526vni/introducing_gg_ez_bot/d7i36w3?st=isylm813&sh=7aa61213

**Comment by MattCzyr** [comment]
Thanks for letting me know. Fixed.
